(()=>{'use strict';
const fa=document.documentElement.lang==='fa',T=(en,p)=>fa?p:en,$=id=>document.getElementById(id),canvas=$('sea'),ctx=canvas.getContext('2d'),KEY='seaone-voyage-v2';
const missions=[
 {name:T('Heritage','میراث'),x:170,y:145,title:T('The story starts with people.','داستان از مردم شروع می‌شود.'),copy:T('A campaign team arrives at a fishing port. What is the strongest first step?','تیم کمپین به یک بندر صیادی می‌رسد. بهترین قدم اول چیست؟'),options:[T('Listen to local captains and build the story together.','به ناخداهای محلی گوش بده و داستان را با آن‌ها بساز.'),T('Film first and ask questions later.','اول فیلم‌برداری کن و بعد سؤال بپرس.'),T('Use the same story for every coast.','برای همه سواحل یک داستان یکسان بساز.')],correct:0,lesson:T('Local knowledge gives the story its roots.','دانش محلی به داستان ریشه می‌دهد.')},
 {name:T('Build','ساخت'),x:410,y:100,title:T('Prepare the vessel.','شناور را آماده کن.'),copy:T('The mission is ready. Which preparation protects the crew and the return?','مأموریت آماده است. کدام آماده‌سازی از خدمه و بازگشت محافظت می‌کند؟'),options:[T('Carry only the mission equipment.','فقط تجهیزات مأموریت را همراه ببر.'),T('Brief the crew, check safety equipment and plan a reserve.','خدمه را توجیه کن، تجهیزات ایمنی را بررسی کن و ذخیره پیش‌بینی کن.'),T('Skip the checks to leave sooner.','برای حرکت زودتر، بررسی‌ها را کنار بگذار.')],correct:1,lesson:T('Preparation belongs before departure. Real trips need qualified supervision.','آماده‌سازی پیش از حرکت انجام می‌شود. سفر واقعی به نظارت متخصص نیاز دارد.')},
 {name:T('Navigate','ناوبری'),x:720,y:180,title:T('A weather decision.','تصمیم در برابر تغییر هوا.'),copy:T('In this fictional route, a squall approaches. What is the responsible choice?','در این مسیر خیالی، تندباد نزدیک می‌شود. انتخاب مسئولانه چیست؟'),options:[T('Race the squall for a faster score.','برای امتیاز بیشتر با تندباد مسابقه بده.'),T('Keep going because the mission matters most.','چون مأموریت مهم‌تر است، ادامه بده.'),T('Pause, assess the conditions and choose the protected route.','توقف کن، شرایط را ارزیابی کن و مسیر محافظت‌شده را انتخاب کن.')],correct:2,lesson:T('A schedule never replaces a safety decision.','برنامه زمانی جای تصمیم ایمن را نمی‌گیرد.')},
 {name:T('Care','مراقبت'),x:680,y:420,title:T('Leave a better sea.','دریا را بهتر باقی بگذار.'),copy:T('Your group finishes a shore workshop. What should happen next?','گروه شما کارگاه ساحلی را تمام کرده است. قدم بعدی چیست؟'),options:[T('Collect the waste safely and follow local environmental guidance.','پسماند را ایمن جمع‌آوری کن و راهنمای محیط‌زیستی محلی را رعایت کن.'),T('Leave the materials for the next group.','مواد باقی‌مانده را برای گروه بعد رها کن.'),T('Feed wildlife for a better photo.','برای عکس بهتر به حیات‌وحش غذا بده.')],correct:0,lesson:T('Participation includes caring for the place that hosts it.','مشارکت، مراقبت از میزبان تجربه را هم شامل می‌شود.')},
 {name:T('Harbour','بندر'),x:190,y:405,title:T('Bring the learning home.','آموخته‌ها را به خانه برگردان.'),copy:T('You return to the harbour. How does the next voyage improve?','به بندر برگشته‌ای. سفر بعدی چگونه بهتر می‌شود؟'),options:[T('Keep only the best photos.','فقط بهترین عکس‌ها را نگه دار.'),T('Review decisions with the crew and record what to improve.','تصمیم‌ها را با خدمه مرور کن و نکات بهبود را ثبت کن.'),T('Repeat the route without a debrief.','بدون مرور، مسیر را تکرار کن.')],correct:1,lesson:T('A good return includes shared learning.','بازگشت خوب، یادگیری مشترک را هم در بر می‌گیرد.')}
];
const reefs=[{x:310,y:280,r:40},{x:565,y:245,r:42},{x:470,y:430,r:30}];
const fresh=()=>({version:2,index:0,x:90,y:310,fuel:100,hull:100,points:0,answers:[],retries:0,mode:'intro',distance:0});let guideIndex=0;let s=fresh(),keys={},auto=false,running=false,last=0,saveClock=0,hitCooldown=0,erasePending=false;
try{const a=JSON.parse(localStorage.getItem(KEY));if(a&&a.version===2&&Number.isInteger(a.index)&&a.index>=0&&a.index<=5&&a.index===a.answers?.length&&['intro','travel','task','complete','failed'].includes(a.mode)&&[a.x,a.y,a.fuel,a.hull,a.points,a.retries,a.distance].every(Number.isFinite)&&a.fuel>=0&&a.fuel<=100&&a.hull>=0&&a.hull<=100&&a.x>=20&&a.x<=880&&a.y>=20&&a.y<=520&&a.answers.every((x,i)=>x===missions[i].correct)){s=a;s.points=a.index*20;}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));$('saved').textContent=T('Progress saved on this browser.','پیشرفت در این مرورگر ذخیره شد.')}catch{$('saved').textContent=T('Storage unavailable. Keep this page open to retain progress.','ذخیره‌سازی در دسترس نیست؛ برای حفظ پیشرفت صفحه را باز نگه دار.')}}
function announce(t){$('status').textContent=t}
function pause(){running=false;auto=false;keys={};$('pause').textContent=T('Resume','ادامه');save()}
function render(){const active=s.mode!=='intro'&&s.mode!=='complete';$('intro').hidden=s.mode!=='intro';$('play').hidden=!active;$('finish').hidden=s.mode!=='complete';$('fuel').textContent=Math.ceil(s.fuel);$('hull').textContent=Math.ceil(s.hull);$('points').textContent=s.points;$('step').textContent=Math.min(5,s.index+1)+' / 5';$('islands').innerHTML=missions.map((m,i)=>`<li class="${i<s.index?'done':i===s.index?'current':''}">${i<s.index?'✓':String(i+1).padStart(2,'0')}<br>${m.name}</li>`).join('');$('task').hidden=s.mode!=='task';$('failure').hidden=s.mode!=='failed';$('controls').hidden=s.mode!=='travel';$('target').textContent=s.mode==='travel'?T('Reach the gold ring: ','به حلقه طلایی برس: ')+missions[s.index].name:s.mode==='failed'?T('Resources exhausted. Restart the voyage with a new plan.','ذخایر تمام شد. سفر را با برنامه تازه شروع کن.'):T('Complete this island’s decision to continue.','برای ادامه، تصمیم این جزیره را کامل کن.');if(s.mode==='task'){const m=missions[s.index];$('taskTitle').textContent=m.title;$('taskCopy').textContent=m.copy;$('options').replaceChildren();m.options.forEach((t,i)=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>answer(i);$('options').append(b)})}if(s.mode==='complete'){const score=Math.max(0,Math.round(.6*s.hull+.4*s.fuel-s.retries*3));$('score').textContent=score+' / 100';$('result').textContent=T('Five islands completed · 100 learning points. Your rank: Captain.','پنج جزیره کامل شد · ۱۰۰ امتیاز یادگیری. رتبه تو: ناخدا.');$('lessons').innerHTML=missions.map(m=>`<li><b>${m.name}</b><br>${m.lesson}</li>`).join('');$('quality').textContent=T('Voyage score reflects remaining resources and decision retries. Learning points unlock through completed islands.','امتیاز سفر به ذخایر باقی‌مانده و تلاش‌های تصمیم‌گیری بستگی دارد. امتیاز یادگیری با تکمیل جزیره‌ها باز می‌شود.')};draw(0)}
function start(){if(s.mode==='intro')s.mode='travel';running=s.mode==='travel';$('pause').textContent=T('Pause','توقف');render();save();canvas.focus();announce(T('Use arrow keys or the buttons. Avoid the reefs. Guided mode can help.','با کلیدهای جهت یا دکمه‌ها حرکت کن. از صخره‌ها فاصله بگیر. حالت راهنما هم در دسترس است.'))}
function arrive(){running=false;auto=false;keys={};s.mode='task';save();render();$('taskTitle').focus();announce(T('Island reached. Choose your next decision.','به جزیره رسیدی. تصمیم بعدی را انتخاب کن.'))}
function answer(i){if(s.mode!=='task')return;const m=missions[s.index];if(i!==m.correct){s.retries++;save();announce(T('Try again. ','دوباره تلاش کن. ')+m.lesson);return}s.answers.push(i);s.index++;guideIndex=0;s.points=s.index*20;s.fuel=Math.min(100,s.fuel+12);s.hull=Math.min(100,s.hull+6);s.mode=s.index===5?'complete':'travel';running=s.mode==='travel';$('pause').textContent=T('Pause','توقف');save();render();announce(m.lesson+' '+T('+20 learning points.','۲۰+ امتیاز یادگیری.'));if(s.mode==='complete'){$('finishTitle').focus()}else canvas.focus()}
function restart(){pause();s=fresh();erasePending=false;$('restart').textContent=T('Start a new voyage','شروع سفر تازه');render();save()}
function update(dt){if(!running||s.mode!=='travel')return;hitCooldown=Math.max(0,hitCooldown-dt);s.fuel=Math.max(0,s.fuel-dt*.10);const goal=missions[s.index];let dx=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),dy=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0);if(auto){const route=s.index===4?[{x:680,y:510},{x:310,y:510},goal]:[goal];let target=route[Math.min(guideIndex,route.length-1)];if(Math.hypot(target.x-s.x,target.y-s.y)<18&&guideIndex<route.length-1){guideIndex++;target=route[guideIndex]}dx=target.x-s.x;dy=target.y-s.y;}
const mag=Math.hypot(dx,dy);if(mag>0){const oldX=s.x,oldY=s.y;s.x=Math.max(24,Math.min(876,s.x+dx/mag*95*dt));s.y=Math.max(24,Math.min(516,s.y+dy/mag*95*dt));s.distance+=Math.hypot(s.x-oldX,s.y-oldY);s.fuel=Math.max(0,s.fuel-dt*.30);for(const r of reefs){const d=Math.hypot(s.x-r.x,s.y-r.y);if(d<r.r+14){const ux=(s.x-r.x)/(d||1),uy=(s.y-r.y)/(d||1);s.x=r.x+ux*(r.r+15);s.y=r.y+uy*(r.r+15);if(!hitCooldown){s.hull=Math.max(0,s.hull-10);hitCooldown=1.5;announce(T('Reef contact: hull −10. Steer around the rocks.','برخورد با صخره: بدنه ۱۰−. مسیر را دور صخره ادامه بده.'))}}}}
if(s.fuel<=0||s.hull<=0){s.mode='failed';pause();render();announce(T('Voyage paused at the rescue screen. Start a new voyage.','سفر متوقف شد. یک سفر تازه شروع کن.'));return}if(Math.hypot(s.x-goal.x,s.y-goal.y)<35){arrive();return}saveClock+=dt;if(saveClock>2){saveClock=0;save()}$('fuel').textContent=Math.ceil(s.fuel);$('hull').textContent=Math.ceil(s.hull)}
function draw(t){ctx.fillStyle='#0b3045';ctx.fillRect(0,0,900,540);ctx.strokeStyle='#17485b';for(let y=10;y<540;y+=28){ctx.beginPath();for(let x=0;x<=900;x+=16){const yy=y+Math.sin(x/65+t*.5+y)*4;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}ctx.setLineDash([3,9]);ctx.strokeStyle='#547382';ctx.beginPath();ctx.moveTo(90,310);missions.forEach(m=>ctx.lineTo(m.x,m.y));ctx.stroke();ctx.setLineDash([]);reefs.forEach(r=>{ctx.fillStyle='#395464';ctx.beginPath();ctx.ellipse(r.x,r.y,r.r,r.r*.75,.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#76939c';ctx.stroke()});missions.forEach((m,i)=>{ctx.fillStyle=i<s.index?'#71b99e':'#a6b199';ctx.beginPath();ctx.ellipse(m.x,m.y,36,24,-.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=i===s.index?'#d8b982':'#536f70';ctx.lineWidth=i===s.index?4:1;ctx.beginPath();ctx.arc(m.x,m.y,44,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#071b29';ctx.font='bold 17px Arial';ctx.textAlign='center';ctx.fillText(i<s.index?'✓':String(i+1),m.x,m.y+6);ctx.fillStyle='#f7f5ed';ctx.font=fa?'16px Vazir':'15px Arial';ctx.fillText(m.name,m.x,m.y+65)});ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle='#f7f5ed';ctx.beginPath();ctx.moveTo(0,-20);ctx.lineTo(12,12);ctx.quadraticCurveTo(0,24,-12,12);ctx.closePath();ctx.fill();ctx.fillStyle='#d8b982';ctx.fillRect(-8,-2,16,12);ctx.fillStyle='#071b29';ctx.fillRect(-5,1,10,5);ctx.fillRect(-11,17,5,7);ctx.fillRect(6,17,5,7);ctx.restore();ctx.lineWidth=1}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;update(dt);if(s.mode==='travel')draw(reduced?0:now/1000);requestAnimationFrame(frame)}
$('start').onclick=start;$('guide').onclick=()=>{auto=!auto;guideIndex=s.index===4?(s.x<340?2:s.y>490?1:0):0;running=true;$('pause').textContent=T('Pause','توقف');announce(auto?T('Guide enabled. You still choose every island decision.','راهنما فعال شد؛ تصمیم هر جزیره با توست.'):T('Manual steering enabled.','کنترل دستی فعال شد.'))};$('pause').onclick=()=>{if(running){pause();announce(T('Paused. Your fuel is safe.','متوقف شد. سوخت مصرف نمی‌شود.'))}else{running=s.mode==='travel';$('pause').textContent=T('Pause','توقف');announce(T('Voyage resumed.','سفر ادامه یافت.'))}};$('retry').onclick=restart;$('again').onclick=restart;$('restart').onclick=()=>{if(!erasePending){erasePending=true;$('restart').textContent=T('Confirm: erase progress','تأیید: پاک‌کردن پیشرفت');return}restart()};
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();if(s.mode!=='travel')return;b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;auto=false;running=true;$('pause').textContent=T('Pause','توقف')};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{keys[b.dataset.key]=false}}
window.addEventListener('keydown',e=>{if(s.mode!=='travel'||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)||e.target.matches('input,select,textarea'))return;e.preventDefault();if(e.key===' '){$('pause').click();return}keys[e.key]=true;auto=false;running=true;$('pause').textContent=T('Pause','توقف')});window.addEventListener('keyup',e=>{keys[e.key]=false});window.addEventListener('blur',()=>pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',save);window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data==='seaone-pause')pause()});
$('resume').hidden=s.mode==='intro';$('resume').onclick=start;if(s.mode!=='intro'){$('intro').hidden=false;$('play').hidden=true;$('finish').hidden=true;$('start').hidden=true;$('introTitle').textContent=T('Your voyage is waiting.','سفرت منتظر توست.')}else render();draw(0);requestAnimationFrame(frame);
})();
